Use URI::Parser#unescape instead of URI::decode
URI::decode is deprecated as of Ruby 1.9.2.

See:

- https://github.com/ruby/ruby/commit/238b979f1789f95262a267d8df6239806f2859cc
- https://github.com/rails/rails/commit/76b2d3e33730fce9680d0b6e97df12b1744fb23d

The redefinition of URI to URI::Parser, when defined, was incorrectly
scoped, causing URI::decode not to explode when expected on Ruby
1.9.2+.

This patch switches over to using #unescape and fixes the constant
definition's scope.

It also gets rid of the following warning when running in verbose mode:

lib/sinatra/base.rb:972:in `block in process_route': warning: URI.unescape is obsolete